import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Sidebar from "@/components/Sidebar";
import { getUser } from "@/app/actions/auth";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getUser();

  return (
    <html lang="es">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#020B0F] text-slate-200`}>
        <div className="flex min-h-screen">
          {session && <Sidebar user={session} />}
          <main className={`flex-1 p-8 transition-all duration-300 ${session ? "ml-64" : "p-0"}`}>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
